version: '3.0'

services:
  productpage:
    build: ./productPage/.
    image: 46/productpage
    container_name: 46-productpage
    ports:
      - '9080:9080'
    environment:
      - GROUPO_NUMERO=46
  
  details:
    build: ./details/.
    image: 46/details
    container_name: 46-details
    depends_on: 
      - productpage
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
  
  reviews:
    build: ./practica_creativa2/bookinfo/src/reviews/reviews-wlpcfg/.
    image: 46/reviews
    container_name: 46-reviews
    depends_on: 
      - productpage
    environment:
      - ENABLE_RATINGS=false
      - SERVICE_VERSION=v1 
      - STAR_COLOR=black  
      #para v1: false - v1 - black/red (no importa)
      #para v2: true - v2 - black
      #para v3: true - v3 - red

  ratings:
    build: ./ratings/.
    image: 46/ratings
    container_name: 46-ratings
    depends_on: 
      - reviews
    environment:
      - SERVICE_VERSION=v1
